### ISSUE TITLE
PRs failing due to deprecated V3 artifact actions

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1857]
Blog post announcing change as of 30 Jan 2025: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Possible scenarios where switching to V4 might cause an issue (none seem applicable to the two yml files of ours that require this change): https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

We only use artifact actions for the uploading of test results, so it's my appraisal that this can be changed and tested quite safely.

`tc-admin-portal-test.yml`
```
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for Angular
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' 

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ui/admin-portal

      # Step 4: Run Angular tests using Karma
      - name: Run Angular tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: ui/admin-portal
        env:
          CI: true
      # Step 5: Archive test results if tests fail
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3 👈
        with:
          name: test-results
          path: ui/admin-portal/dist/test-results
```

`tc-gatling-tests.yml`
```
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gatling Tests
        run: ./gradlew performance-test:build
        env:
          DB_URL: ${{ secrets.STAGING_DB_URL }}
          DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}

      - name: Archive Gatling Reports
        uses: actions/upload-artifact@v3 👈
        if: always()
        with:
          name: Gatling Reports
          path: performance-tests/build/reports/gatling
          if-no-files-found: error
```
