### ISSUE TITLE
Investigate other language elastic searching issue

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#360]
As a user
I want to elastic search on other languages in prod
The same as I am able to do in staging

**Comment by sadatmalik** [comment]
The prod re-indexing has not updated the mapping for the other languages property: 

Prod mapping:

```
        "otherLanguages" : {
          "properties" : {
            "minSpokenLevel" : {
              "type" : "long"
            },
            "minWrittenLevel" : {
              "type" : "long"
            },
            "name" : {
              "type" : "text",
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            }
          }
        },
```

Staging:

```
        "otherLanguage" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "otherLanguages" : {
          "type" : "nested",
          "properties" : {
            "_class" : {
              "type" : "keyword",
              "index" : false,
              "doc_values" : false
            },
            "minSpokenLevel" : {
              "type" : "integer"
            },
            "minWrittenLevel" : {
              "type" : "integer"
            },
            "name" : {
              "type" : "text",
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            }
          }
        },
```

**Comment by sadatmalik** [comment]
Summary of differences between Staging and Prod mappings:

```
"_class" Field:
  Staging:
    Type: keyword
    Index: false
    Doc values: false
  Production:
    Type: text
    Keyword field with ignore_above: 256


"ieltsScore" Field:
  Staging:
    Type: double
  Production:
    Type: float


"otherLanguages" Field:
  Staging:
    Type: nested
    Properties:
      "minSpokenLevel": long
      "minWrittenLevel": long
      "name": text
  Production:
    Properties:
      "minSpokenLevel": long
      "minWrittenLevel": long
      "name": text (nested property is not explicitly defined in production)


"_class" Field within "otherLanguages":
  Staging:
    Type: keyword
    Index: false
    Doc values: false
  Production:
    This field is not explicitly defined.


"ieltsScore" Field:
  Staging:
    Type: double
  Production:
    Type: float


"additionalInfo" Field:
  Staging:
    Type: text
  Production:
    Type: text with keyword field
```
