### ISSUE TITLE
Max file size configuration is not picked up in cloud environments

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#941]
This has been HotFixed into production

This Spring config is not being picked up by AWS tasks:

```
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:10MB}
```

That configuration is recognized when running in dev, but not in AWS for some reason.

When uploading large files that are tagged as CV's this can result in a Out of memory error when the CV processing code attempts to load the file into memory for processing.

The workaround solution is to do the file size checking ourselves rather than relying on Spring/Tomcat.
